```yaml
version: '3.8'

services:
  rocio_db:
    image: postgres:15-alpine
    container_name: rocio_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rocio_db
    ports:
      - "5433:5432"
    volumes:
      - rocio_postgres_data:/var/lib/postgresql/data

volumes:
  rocio_postgres_data:
```
